---
- name: install kubernetes minion
  become: yes
  yum: pkg={{ item }} state=present
  with_items:
    "{{ kube_minion_pkgs }}"

- name: configure base kubernetes
  become: yes
  template:
    src: templates/config.j2
    dest: /etc/kubernetes/config

- name: configure kubelet
  become: yes
  template:
    src: templates/kubelet.j2
    dest: /etc/kubernetes/kubelet

- name: start kubernetes minion services
  become: yes
  service: name={{ item }} state=started enabled=yes
  with_items:
    "{{ kube_minion_services }}"