---
- name: install mesos
  become: yes
  yum: pkg="{{ item }}" state=present
  with_items:
    "{{ mesos_pkgs }}"

- name: start mesos-master services
  become: yes
  service: name="{{ item }}" state=started
  with_items:
    "{{ mesos_master_services }}"

- name: start slave services
  become: yes
  service: name="{{ item }}" state=started
  with_items:
    - mesos-slave
