#
# Mesos slaves
#
# https://registry.hub.docker.com/u/redjack/mesos-slave/
# http://mesos.apache.org/documentation/latest/configuration/
#
slave:
  image: redjack/mesos-slave:0.21.0
  ports:
    - "5051:5051"
  environment:
    MESOS_MASTER: zk://[zookeeper-host]:2181/mesos
    MESOS_LOG_DIR: /var/log
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/local/bin/docker
    - /sys/fs/cgroup:/sys/fs/cgroup
