---
- name: install etcd
  become: yes
  yum: pkg={{ item }} state=present
  with_items:
    "{{ etcd_pkgs }}"

- name: configure etcd
  become: yes
  command: crudini --set /etc/etcd/etcd.conf {{ item }}
  with_items:
    - "member ETCD_NAME default"
    - "member ETCD_DATA_DIR /var/lib/etcd/default.etcd"
    - "member ETCD_LISTEN_CLIENT_URLS http://0.0.0.0:2379"
    - "cluster ETCD_ADVERTISE_CLIENT_URLS http://0.0.0.0:2379"
  notify: restart etcd

- name: start etcd
  become: yes
  service: name=etcd state=started

- name: wait etcd to start
  wait_for: port=2379 delay=10

- name: clean flannel configuration
  become: yes
  shell: "etcdctl rm /atomic.io/network/config ||:"

- name: configure flannel network
  become: yes
  command: etcdctl mk /atomic.io/network/config '{"Network":"172.17.0.0/16"}'
